# Generated by Django 5.2.4 on 2025-07-04 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(validators=[django.core.validators.MinLengthValidator(10, 'This field must contain at least 10 characters.')])),
                ('link', models.URLField()),
            ],
        ),
    ]
