# Generated by Django 5.2.4 on 2025-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carouselimg_contactway_skill_alter_websitecard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimg',
            name='img',
            field=models.ImageField(upload_to='images/Carousel'),
        ),
        migrations.AlterField(
            model_name='contactway',
            name='logo',
            field=models.ImageField(upload_to='images/Logos'),
        ),
        migrations.AlterField(
            model_name='websitecard',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/webCards'),
        ),
    ]
