# Generated by Django 5.2.4 on 2025-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carouselimg_img_alter_contactway_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecard',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
