# Generated by Django 5.2.4 on 2025-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_websitecard_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
